# Creating a new user
POST  http://localhost:3000/api/user/authorization HTTP/1.1
Content-Type: application/json

{
  "name": "Vlad Ivanov",
  "email": "Vlad@mail.com",
  "password": "1984VI",
  "typeUser": "pro"
}

###
# User authentication
GET   http://localhost:3000/api/user/authentication HTTP/1.1
Content-Type: application/json

{
  "email": "Vlad@mail.com",
  "password": "1984VI"
}

###
# User authentication
GET   http://localhost:3000/api/user/authentication HTTP/1.1
Content-Type: application/json

{
  "email": "Alek@mail.com",
  "password": "1984AI"
}

###
# Checking the state of the user
GET   http://localhost:3000/api/user/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YjFlZjZlMjc4MDZhMDRhNmFlNmFkMSIsImVtYWlsIjoiQWxla0BtYWlsLmNvbSIsIm5hbWUiOiJBbGVrIEl2YW5vdiIsImF2YXRhciI6Ii9zdGF0aWMvaWNvbi11c2VyLnN2ZyIsInR5cGVVc2VyIjoicHJvIiwiaWF0IjoxNzM5NzE0NDI3LCJleHAiOjE3Mzk4MDA4Mjd9.0R9lh4WW9cKj83NnHPB5vc7A3s72fG_rVsAvvuPAlhY

###
# Exit from the closed part of the application
DELETE   http://localhost:3000/api/user/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YjFlOGIwOWM3ZWE1NzAyNjYzZjljNiIsImVtYWlsIjoiQWxla0BtYWlsLmNvbSIsIm5hbWUiOiJBbGVrIEl2YW5vdiIsImlhdCI6MTczOTcxMjY5NSwiZXhwIjoxNzM5Nzk5MDk1fQ.JlCHJose5U-fvEee_gFub2T5apYik-jkppaEvZBInXg
