services:
  six-cities:
    image: mongo:latest
    restart: always
    container_name: ${MONGO_DB}

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}

    ports:
      - ${MONGO_PORT}:27017

    volumes:
      - six.cities.mongo:/data/db

    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh ${HOST}:${MONGO_PORT}/${MONGO_DB} --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  what-to-watch.ui:
    image: mongo-express:latest
    restart: always
    container_name: ${MONGO_DB}.mongo.ui
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@six-cities:${MONGO_PORT}/

volumes:
  six.cities.mongo:
