# Аренда
## Создать новое предложение по аренде
POST http://localhost:5000/api/rent/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YjMyYjZlN2ZlZTE2MTlhZDRkMmI2YSIsImVtYWlsIjoiVmxhZEBtYWlsLmNvbSIsIm5hbWUiOiJWbGFkIEl2YW5vdiIsImF2YXRhciI6Ii9zdGF0aWMvaWNvbi11c2VyLnN2ZyIsInR5cGVVc2VyIjoicHJvIiwiaWF0IjoxNzM5Nzk1MzUxLCJleHAiOjE3Mzk4ODE3NTF9.goYDIZYtEpqyOemcj2oEgNs2efrbafn7eV4phI-SE_s

{
  "name": "Ferst Hotel",
  "description": "This is hotel lacated in the city center near to the square of stars.",
  "city": "Volgograd",
  "preverteringImage": "img/room.jpg",
  "photosHousing": [
    "photo-1.jpg",
    "photo-2.jpg",
    "photo-3.jpg",
    "photo-4.jpg",
    "photo-5.jpg"
  ],
  "premium": false,
  "favorites": false,
  "typeHousing": "hotel",
  "numberRoom": 6,
  "numberGuest": 9,
  "priceRent": 12752,
  "comfort": ["Baby seat","Washer","Towels"],
  "idUser": "123-321",
  "coordinates": [
    52.370216,
    4.895168
  ]
}

###
## Редактирование предложения по аренде
PATCH  http://localhost:5000/api/rent/94df4f26-e5e4-49f6-8bff-809f339787ee HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YjFlZjZlMjc4MDZhMDRhNmFlNmFkMSIsImVtYWlsIjoiQWxla0BtYWlsLmNvbSIsIm5hbWUiOiJBbGVrIEl2YW5vdiIsImF2YXRhciI6Ii9zdGF0aWMvaWNvbi11c2VyLnN2ZyIsInR5cGVVc2VyIjoicHJvIiwiaWF0IjoxNzM5NzE0NDI3LCJleHAiOjE3Mzk4MDA4Mjd9.0R9lh4WW9cKj83NnHPB5vc7A3s72fG_rVsAvvuPAlhY

{
  "priceRent": 1000,
  "comfort": ["Baby seat"]
}

###
## Удаление информации по аренде
DELETE  http://localhost:5000/api/rent/94df4f26-e5e4-49f6-8bff-809f339787ee HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YjFlZjZlMjc4MDZhMDRhNmFlNmFkMSIsImVtYWlsIjoiQWxla0BtYWlsLmNvbSIsIm5hbWUiOiJBbGVrIEl2YW5vdiIsImF2YXRhciI6Ii9zdGF0aWMvaWNvbi11c2VyLnN2ZyIsInR5cGVVc2VyIjoicHJvIiwiaWF0IjoxNzM5NzE0NDI3LCJleHAiOjE3Mzk4MDA4Mjd9.0R9lh4WW9cKj83NnHPB5vc7A3s72fG_rVsAvvuPAlhY

###
## Получение детальной информации по аренде
GET http://localhost:5000/api/rent/127f5fe8-257e-4cce-9af9-05f5e99af262 HTTP/1.1

###
## Список предложений по аренде
GET   http://localhost:5000/api/rent/ HTTP/1.1

###
## Премиальные предложения по аренде для города
GET   http://localhost:5000/api/rent/premium?city=Brussels HTTP/1.1

###
## Избранные предложения по аренде для города
GET   http://localhost:5000/api/rent/favorit HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YjMyYjZlN2ZlZTE2MTlhZDRkMmI2YSIsImVtYWlsIjoiVmxhZEBtYWlsLmNvbSIsIm5hbWUiOiJWbGFkIEl2YW5vdiIsImF2YXRhciI6Ii9zdGF0aWMvaWNvbi11c2VyLnN2ZyIsInR5cGVVc2VyIjoicHJvIiwiaWF0IjoxNzM5Nzk1MzUxLCJleHAiOjE3Mzk4ODE3NTF9.goYDIZYtEpqyOemcj2oEgNs2efrbafn7eV4phI-SE_s

###
## Добавление и удаление предложения по аренде в/из избранного
POST    http://localhost:5000/api/rent/favorit/127f5fe8-257e-4cce-9af9-05f5e99af262 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YjMyYjZlN2ZlZTE2MTlhZDRkMmI2YSIsImVtYWlsIjoiVmxhZEBtYWlsLmNvbSIsIm5hbWUiOiJWbGFkIEl2YW5vdiIsImF2YXRhciI6Ii9zdGF0aWMvaWNvbi11c2VyLnN2ZyIsInR5cGVVc2VyIjoicHJvIiwiaWF0IjoxNzM5Nzk1MzUxLCJleHAiOjE3Mzk4ODE3NTF9.goYDIZYtEpqyOemcj2oEgNs2efrbafn7eV4phI-SE_s
