# Комментарии
## Добавление комментария
POST http://localhost:5000/api/comment/ HTTP/1.1
Content-Type: application/json

{
  "text": "For Dombie.",
  "rating": 9,
  "idUser": "123-321",
  "idRent": "d7cecf35-038c-426a-aebc-4a9d41f8c40e"
}

###
## Список комментариев
GET  http://localhost:5000/api/comment/a29e9792-419d-4c11-9a58-013e0ce68349 HTTP/1.1
