# Комментарии
## Добавление комментария
POST http://localhost:5000/api/comment/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YjFlZjZlMjc4MDZhMDRhNmFlNmFkMSIsImVtYWlsIjoiQWxla0BtYWlsLmNvbSIsIm5hbWUiOiJBbGVrIEl2YW5vdiIsImF2YXRhciI6Ii9zdGF0aWMvaWNvbi11c2VyLnN2ZyIsInR5cGVVc2VyIjoicHJvIiwiaWF0IjoxNzM5NzE0NDI3LCJleHAiOjE3Mzk4MDA4Mjd9.0R9lh4WW9cKj83NnHPB5vc7A3s72fG_rVsAvvuPAlhY


{
  "text": "For Saratov",
  "rating": 5,
  "idRent": "94df4f26-e5e4-49f6-8bff-809f339787ee"
}

###
## Список комментариев
GET  http://localhost:5000/api/comment/d7cecf35-038c-426a-aebc-4a9d41f8c40e HTTP/1.1
